# Generated by Django 2.0.7 on 2019-11-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accolade',
            options={'verbose_name': 'Accolade', 'verbose_name_plural': 'Accolade'},
        ),
        migrations.RemoveField(
            model_name='player',
            name='bio_link',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hometown_lat',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hometown_long',
        ),
        migrations.AddField(
            model_name='record',
            name='bio_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accolade',
            name='Accolade',
            field=models.IntegerField(choices=[('0', 'First Team'), ('1', 'Second Team'), ('2', 'Third Team'), ('3', 'Rookie Team'), ('4', 'Honorable Mention'), ('5', 'Freshman Team')]),
        ),
    ]
